
name: Notebook smoke test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt nbconvert
      - name: Execute 01_data_overview
        run: jupyter nbconvert --to notebook --execute notebooks/01_data_overview.ipynb --output /tmp/out.ipynb
